name: Build and Release Telegram Bot API

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., 1.0.0)'
        required: true
        type: string

env:
  VERSION: ${{ github.event.inputs.version }}

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    # Add this permissions block:
    permissions:
      contents: write
      actions: read
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get upgrade -y
        sudo apt-get install -y make git zlib1g-dev libssl-dev gperf cmake clang-18 libc++-18-dev libc++abi-18-dev gh

    - name: Clone Telegram Bot API
      run: |
        git clone --recursive https://github.com/tdlib/telegram-bot-api.git

    - name: Build Telegram Bot API
      run: |
        cd telegram-bot-api
        rm -rf build
        mkdir build
        cd build
        CXXFLAGS="-stdlib=libc++" CC=/usr/bin/clang-18 CXX=/usr/bin/clang++-18 cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=.. ..
        cmake --build . --target install

    - name: Release bare binary with GitHub CLI
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: >-
        gh release create "v${{ env.VERSION }}"
        "telegram-bot-api/bin/telegram-bot-api#telegram-bot-api"
        --generate-notes
